name: rust
on: [push, pull_request]

jobs:
  setup_env:
    name: rust
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "clangd/clangd"
          latest: true
          fileName: "*"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./gopls/gopls_${{ runner.os }}.exe
