name: upload_to_pypi
on: [push, pull_request]

jobs:
  setup_env:
    name: upload_to_pypi
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'pypi')"
    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/ECY_exe

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "JimmyHuang454/ECY_exe"
          latest: true
          out-file-path: "exes"
          fileName: "*"

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "clangd/clangd"
          latest: true
          out-file-path: "clangd"
          fileName: "*"

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "rust-analyzer/rust-analyzer"
          latest: true
          out-file-path: "rust_analyzer"
          fileName: "*"

      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "sumneko/lua-language-server"
          latest: true
          out-file-path: "lua"
          fileName: "*"

      - name: Build pypi
        env:
          PYPI: ${{ secrets.PYPI }}
        run: |
          python up.py

      # - name: Publish distribution to PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI }}
      #     packages_dir: pypi/ECY_${{ runner.os }}_main_dir/ECY_${{ runner.os }}_main/dist
