name: neovim
on: [push, pull_request]

jobs:
  setup_env:
    name: neovim
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        neovim_version: ["nightly", "stable", "v0.5.0"]
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'test')"
    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/EasyCompleteYou
          path: ECY

      - name: Checkout ultisnips
        uses: actions/checkout@v2
        with:
          repository: SirVer/ultisnips
          path: ultisnips

      - name: Checkout snippets
        uses: actions/checkout@v2
        with:
          repository: honza/vim-snippets
          path: snippets

      - name: Install Python
        uses: actions/setup-python@v1

      - name: ls
        run: |
          ls

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Run unit tests(Windows)
        if: runner.os == 'Windows'
        run: |
          pip3 install jedi_language_server
          jedi-language-server --help
          python ./ECY/test/ECY_test.py --is_neovim "true" --vim_exe "${{ steps.vim.outputs.executable }}"

      - name: Run unit tests(Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          sudo pip3 install jedi_language_server
          jedi-language-server --help
          sudo python ./ECY/test/ECY_test.py --is_neovim "true" --vim_exe "${{ steps.vim.outputs.executable }}"
