name: vim
on: [push, pull_request]

jobs:
  setup_env:
    name: vim
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        # vim has no stable tag.
        vim_version: ["nightly", "v8.2.0008", "v8.1.1578", "v8.2.1419"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/EasyCompleteYou
          path: ECY

      - name: Checkout ultisnips
        uses: actions/checkout@v2
        with:
          repository: SirVer/ultisnips
          path: ultisnips

      - name: Checkout snippets
        uses: actions/checkout@v2
        with:
          repository: honza/vim-snippets
          path: snippets

      - name: Install Python
        uses: actions/setup-python@v1

      - name: ls
        run: |
          ls

      - name: Install Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: false
          version: ${{ matrix.vim_version }}

      - name: Run unit tests(Windows)
        if: runner.os == 'Windows'
        run: |
          pip3 install jedi_language_server
          jedi-language-server --help
          python ./ECY/test/ECY_test.py --is_neovim "false" --vim_exe "${{ steps.vim.outputs.executable }}"

      - name: Run unit tests(Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          sudo pip3 install jedi_language_server
          jedi-language-server --help
          sudo python ./ECY/test/ECY_test.py --is_neovim "false" --vim_exe "${{ steps.vim.outputs.executable }}"


