name: ECY CI in Windows
on: [push, pull_request]

jobs:
  setup_env:
    name: Unit tests
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        # neovim: [false, true]
        # install_python: [false, true]
    runs-on: ${{ matrix.os }}
    steps:
      #############
      #  clone  #
      #############
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/EasyCompleteYou
          path: ECY

      - name: Checkout test framework
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/vim-themis
          path: vim-themis

      #################
      #  install vim  #
      #################
      - name: Install Vim or Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: false

      ####################
      #  Install Python  #
      ####################
      - name: Install Python
        uses: actions/setup-python@v1

      - name: Run unit tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          PROFILE_LOG: profile.txt
        run: |
          cd ./ECY/test
          echo "${THEMIS_VIM}"
          # ../../vim-themis/bin/themis .
